USE stonx;
INSERT INTO Stocks(symbol,company_name) VALUES ('AAPL','Apple');
INSERT INTO Stocks(symbol,company_name) VALUES ('ABBV','AbbVie');
INSERT INTO Stocks(symbol,company_name) VALUES ('ABT','Abbott');
INSERT INTO Stocks(symbol,company_name) VALUES ('ACN','Accenture');
INSERT INTO Stocks(symbol,company_name) VALUES ('ADBE','Adobe');
INSERT INTO Stocks(symbol,company_name) VALUES ('AIG','AIG');
INSERT INTO Stocks(symbol,company_name) VALUES ('AMGN','Amgen');
INSERT INTO Stocks(symbol,company_name) VALUES ('AMT','American Tower');
INSERT INTO Stocks(symbol,company_name) VALUES ('AMZN','Amazon');
INSERT INTO Stocks(symbol,company_name) VALUES ('AVGO','Broadcom');
INSERT INTO Stocks(symbol,company_name) VALUES ('AXP','American Express');
INSERT INTO Stocks(symbol,company_name) VALUES ('BA','Boeing');
INSERT INTO Stocks(symbol,company_name) VALUES ('BAC','Bank of America');
INSERT INTO Stocks(symbol,company_name) VALUES ('BK','BNY Mellon');
INSERT INTO Stocks(symbol,company_name) VALUES ('BKNG','Booking Holdings');
INSERT INTO Stocks(symbol,company_name) VALUES ('BLK','BlackRock');
INSERT INTO Stocks(symbol,company_name) VALUES ('BMY','Bristol Myers Squibb');
INSERT INTO Stocks(symbol,company_name) VALUES ('BRK.B','Berkshire Hathaway');
INSERT INTO Stocks(symbol,company_name) VALUES ('C','Citigroup');
INSERT INTO Stocks(symbol,company_name) VALUES ('CAT','Caterpillar');
INSERT INTO Stocks(symbol,company_name) VALUES ('CHTR','Charter Communications');
INSERT INTO Stocks(symbol,company_name) VALUES ('CL','Colgate-Palmolive');
INSERT INTO Stocks(symbol,company_name) VALUES ('CMCSA','Comcast');
INSERT INTO Stocks(symbol,company_name) VALUES ('COF','Capital One');
INSERT INTO Stocks(symbol,company_name) VALUES ('COP','ConocoPhillips');
INSERT INTO Stocks(symbol,company_name) VALUES ('COST','Costco');
INSERT INTO Stocks(symbol,company_name) VALUES ('CRM','Salesforce');
INSERT INTO Stocks(symbol,company_name) VALUES ('CSCO','Cisco');
INSERT INTO Stocks(symbol,company_name) VALUES ('CVS','CVS Health');
INSERT INTO Stocks(symbol,company_name) VALUES ('CVX','Chevron');
INSERT INTO Stocks(symbol,company_name) VALUES ('DD','DuPont');
INSERT INTO Stocks(symbol,company_name) VALUES ('DHR','Danaher');
INSERT INTO Stocks(symbol,company_name) VALUES ('DIS','Disney');
INSERT INTO Stocks(symbol,company_name) VALUES ('DOW','Dow');
INSERT INTO Stocks(symbol,company_name) VALUES ('DUK','Duke Energy');
INSERT INTO Stocks(symbol,company_name) VALUES ('EMR','Emerson');
INSERT INTO Stocks(symbol,company_name) VALUES ('EXC','Exelon');
INSERT INTO Stocks(symbol,company_name) VALUES ('F','Ford');
INSERT INTO Stocks(symbol,company_name) VALUES ('FB','Meta');
INSERT INTO Stocks(symbol,company_name) VALUES ('FDX','FedEx');
INSERT INTO Stocks(symbol,company_name) VALUES ('GD','General Dynamics');
INSERT INTO Stocks(symbol,company_name) VALUES ('GE','GE');
INSERT INTO Stocks(symbol,company_name) VALUES ('GILD','Gilead');
INSERT INTO Stocks(symbol,company_name) VALUES ('GM','GM');
INSERT INTO Stocks(symbol,company_name) VALUES ('GOOG','Alphabet (Class C)');
INSERT INTO Stocks(symbol,company_name) VALUES ('GOOGL','Alphabet (Class A)');
INSERT INTO Stocks(symbol,company_name) VALUES ('GS','Goldman Sachs');
INSERT INTO Stocks(symbol,company_name) VALUES ('HD','Home Depot');
INSERT INTO Stocks(symbol,company_name) VALUES ('HON','Honeywell');
INSERT INTO Stocks(symbol,company_name) VALUES ('IBM','IBM');
INSERT INTO Stocks(symbol,company_name) VALUES ('INTC','Intel');
INSERT INTO Stocks(symbol,company_name) VALUES ('JNJ','Johnson & Johnson');
INSERT INTO Stocks(symbol,company_name) VALUES ('JPM','JPMorgan Chase');
INSERT INTO Stocks(symbol,company_name) VALUES ('KHC','Kraft Heinz');
INSERT INTO Stocks(symbol,company_name) VALUES ('KO','Coca-Cola');
INSERT INTO Stocks(symbol,company_name) VALUES ('LIN','Linde');
INSERT INTO Stocks(symbol,company_name) VALUES ('LLY','Lilly');
INSERT INTO Stocks(symbol,company_name) VALUES ('LMT','Lockheed Martin');
INSERT INTO Stocks(symbol,company_name) VALUES ('LOW','Lowe''s');
INSERT INTO Stocks(symbol,company_name) VALUES ('MA','Mastercard');
INSERT INTO Stocks(symbol,company_name) VALUES ('MCD','McDonald''s');
INSERT INTO Stocks(symbol,company_name) VALUES ('MDLZ','Mondelēz International');
INSERT INTO Stocks(symbol,company_name) VALUES ('MDT','Medtronic');
INSERT INTO Stocks(symbol,company_name) VALUES ('MET','MetLife');
INSERT INTO Stocks(symbol,company_name) VALUES ('MMM','3M');
INSERT INTO Stocks(symbol,company_name) VALUES ('MO','Altria');
INSERT INTO Stocks(symbol,company_name) VALUES ('MRK','Merck');
INSERT INTO Stocks(symbol,company_name) VALUES ('MS','Morgan Stanley');
INSERT INTO Stocks(symbol,company_name) VALUES ('MSFT','Microsoft');
INSERT INTO Stocks(symbol,company_name) VALUES ('NEE','NextEra Energy');
INSERT INTO Stocks(symbol,company_name) VALUES ('NFLX','Netflix');
INSERT INTO Stocks(symbol,company_name) VALUES ('NKE','Nike');
INSERT INTO Stocks(symbol,company_name) VALUES ('NVDA','Nvidia');
INSERT INTO Stocks(symbol,company_name) VALUES ('ORCL','Oracle');
INSERT INTO Stocks(symbol,company_name) VALUES ('PEP','PepsiCo');
INSERT INTO Stocks(symbol,company_name) VALUES ('PFE','Pfizer');
INSERT INTO Stocks(symbol,company_name) VALUES ('PG','Procter & Gamble');
INSERT INTO Stocks(symbol,company_name) VALUES ('PM','Philip Morris International');
INSERT INTO Stocks(symbol,company_name) VALUES ('PYPL','PayPal');
INSERT INTO Stocks(symbol,company_name) VALUES ('QCOM','Qualcomm');
INSERT INTO Stocks(symbol,company_name) VALUES ('RTX','Raytheon Technologies');
INSERT INTO Stocks(symbol,company_name) VALUES ('SBUX','Starbucks');
INSERT INTO Stocks(symbol,company_name) VALUES ('SCHW','Charles Schwab');
INSERT INTO Stocks(symbol,company_name) VALUES ('SO','Southern Company');
INSERT INTO Stocks(symbol,company_name) VALUES ('SPG','Simon');
INSERT INTO Stocks(symbol,company_name) VALUES ('T','AT&T');
INSERT INTO Stocks(symbol,company_name) VALUES ('TGT','Target');
INSERT INTO Stocks(symbol,company_name) VALUES ('TMO','Thermo Fisher Scientific');
INSERT INTO Stocks(symbol,company_name) VALUES ('TMUS','T-Mobile');
INSERT INTO Stocks(symbol,company_name) VALUES ('TSLA','Tesla');
INSERT INTO Stocks(symbol,company_name) VALUES ('TXN','Texas Instruments');
INSERT INTO Stocks(symbol,company_name) VALUES ('UNH','UnitedHealth');
INSERT INTO Stocks(symbol,company_name) VALUES ('UNP','Union Pacific');
INSERT INTO Stocks(symbol,company_name) VALUES ('UPS','United Parcel Service');
INSERT INTO Stocks(symbol,company_name) VALUES ('USB','U.S. Bank');
INSERT INTO Stocks(symbol,company_name) VALUES ('V','Visa');
INSERT INTO Stocks(symbol,company_name) VALUES ('VZ','Verizon');
INSERT INTO Stocks(symbol,company_name) VALUES ('WBA','Walgreens Boots Alliance');
INSERT INTO Stocks(symbol,company_name) VALUES ('WFC','Wells Fargo');
INSERT INTO Stocks(symbol,company_name) VALUES ('WMT','Walmart');
INSERT INTO Stocks(symbol,company_name) VALUES ('XOM','ExxonMobil');
INSERT INTO Stocks(symbol,company_name) VALUES ('SPY','S&P 500');
